# Marketplace specific settings
marketplace:
  base-url: http://localhost:8080
  marketplace-db: jdbc:hsqldb:file:database/marketplace;shutdown=true;hsqldb.default_table_type=cached
  system-db: jdbc:hsqldb:file:database/system;shutdown=true;hsqldb.default_table_type=cached
  title: DAWN Plug-in Marketplace
  footer: Copyright Â© 2016 Diamond Light Source
  catalog-icon: http://localhost:8080/pages/catalog-icon.png
  description: The DAWN Plug-in Marketplace
  wizard-title: DAWN Plug-in Catalog
  wizard-icon: http://localhost:8080/pages/wizard-icon.png
  max-recent-solutions: 12
  solutions-folder: solutions
  pages-folder: pages
  featured:
    maximum: 3
    solutions: 1,2,3,4,5,6,7,8,9,10

multipart:
  maxFileSize: -1
  maxRequestSize: -1

spring:
# Enable ANSI logging if possible
  output:
    ansi:
      enabled: detect
# Integration with social networks
  social:
    twitter:
      app-id: XHYkM7qaRCEpgAcS7OesQfSuC
      app-secret: WiWkeFOCbhPkCqvGEMVdY01yMTZ12tZys3RuJQYmOGSkuUPSeE
    google:
      app-id: 755195282704-qirggod5kig0q3u0p1ic8e4p3hp586ql.apps.googleusercontent.com
      app-secret: rYMUytK8ZIQR8gA9o37c1JYt
    github:
      app-id: 922a8751a6251b43e03a
      app-secret: 83e7c1b55dfce9d4f4aa05845ed2d4859bf6cbfe

# Useful when developing, should be set to "true" when in production
  thymeleaf:
    cache: false

      